sudo: false

language:
    - node_js

node_js:
    - '10.14.2'

git:
    submodules: false

before_install:
    - git config --global user.name "XWP (bot)"
    - git config --global user.email "tech@xwp.co"

install:
    - yarn install

script:
    - yarn run eslint
